import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';
import { withApiAuthentication } from '../app/lib/.server/auth';

export const onRequest: PagesFunction = async (context) => {
  return withApiAuthentication(
    context.request,
    context.env as unknown as Record<string, string | undefined>,
    async () => {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment -- The server bundle is generated by Remix at build time.
      // @ts-expect-error Remix generates this module as part of the production build.
      const serverBuild = (await import('../build/server')) as unknown as ServerBuild;

      const handler = createPagesFunctionHandler({
        build: serverBuild,
      });

      return handler(context);
    },
  );
};
